Repository recodehive/resume-pitch, pull requests merged in 2024-08, with the labels that each got.

#8 Create varsani2520 unmerged and unlabeled pr.md
  pr_dump/varsani2520 unmerged and unlabeled pr.md
Labels: gssoc, level 2

#7 Create Rajput-xv
  pr_dump/Rajput-xv
Labels: gssoc, level 2

#9 Create EduWeb-Ojas Arora
  pr_dump/EduWeb-Ojas Arora
Labels: gssoc, level 3

#21 PR Merged But Not Given Labels
  pr_dump/Tejashri.md
Labels: gssoc, level 2

#19 Was Merged PR from NestONDC - RishiMondal
  pr_dump/NestONDC - FeedbackPage Aslams2020
Labels: gssoc, level 3

#28 MastanSayyad - PR 3
  pr_dump/PR MastanSayyad.md
Labels: gssoc, level3

#31 RadhikaMalpani1702-Nest ONDC PR's (Rishi Mondel)
  pr_dump/PR Radhika Malpani.md
Labels: help wanted, gssoc, level3

#30 Update from NestONDC - PR2
  pr_dump/NestONDC - FeedbackPage Aslams2020
Labels: gssoc, level2

#29 Pending Merged PR
  pr_dump/Pending merged PR
Labels: gssoc, level2

#27 MastanSayyad - PR 2
  pr_dump/PR MastanSayyad.md
Labels: gssoc, level2

#26 Created nagalakshmi08-pending merged PRs
  pr_dump/nagalakshmi08-pending merged PRs
Labels: gssoc, level3

#24 PR merged but the label was not assigned
  pr_dump/AsmitaMishra24 unlabeled pr.md
Labels: gssoc, level2

#22 PR merged but score not counted and Not added label
  README.md
  pr_dump/dhairyagothi unlabeled
Labels: gssoc, level3

#20 Nest-ondc Prs and some unmerged pr
  pr_dump/nishant0708.md
Labels: gssoc, level3

#18 Create Chaitanya-pr
  pr_dump/Chaitanya-pr
Labels: gssoc, level2

#17 Create Sau-mili NEST Repo
  pr_dump/Sau-mili NEST
Labels: gssoc, level2

#16 Added nonmerged PR links and unassigned issue links
  pr_dump/vansh-codes.md
Labels: gssoc, level3

#15 Lovely Unmerged Pr
  pr_dump/lovely unmerged_pr.md
Labels: gssoc, level3

#13 wrong label
  pr_dump/sakshii00 wrong label
Labels: gssoc, level2

#10 unassigned prs
  pr_dump/mypr
Labels: gssoc, level3

#6 dhruv8433 unmerged and unlabeled pr
  pr_dump/dhruv8433_pr.md
Labels: gssoc, level3

#35 Create Asymtode.md
  pr_dump/Asymtode.md
Labels: gssoc, level3

#33 Dhruv pr
  pr_dump/dhruv.md
Labels: help wanted, gssoc, level3

#37 Update dhruv8433_pr.md
  pr_dump/dhruv8433_pr.md
Labels: gssoc, level3

#41 Update Asymtode.md
  pr_dump/Asymtode.md
Labels: gssoc, level3

#53 updated aditya
  pr_dump/aditya-bhaumik_pr
Labels: gssoc, level2

#48 Create PR jency1.md
  pr_dump/PR jency1.md
Labels: gssoc, level3

#46 Update dhruv8433_pr.md
  pr_dump/dhruv8433_pr.md
Labels: gssoc, level2

#38 Update dhruv.md
  pr_dump/dhruv.md
Labels: gssoc, level3

#45 Update Asymtode.md
  pr_dump/Asymtode.md
Labels: gssoc, level2

#40 Update dhruv8433_pr.md
  pr_dump/dhruv8433_pr.md
Labels: gssoc, level2

#63 PR not merged
  pr_dump/Asymtode.md
Labels: gssoc, level3

#61 PR Not Merged for issue #282 at repository blogzen-OpenSource
  pr_dump/PR Chalsi Jain
Labels: gssoc, level3

#56 Create Husan7.update
  pr_dump/Husan7.update
Labels: gssoc, level3

#49 level 3 pull request not merged yet
  pr_dump/aditya-bhaumik_pr
Labels: gssoc, level3

#55 Create jency1 - PR not merged
  pr_dump/jency1 - PR not merged
Labels: gssoc, level3

#68 Unmerged and also project merged closed PR
  pr_dump/unmerged_pr.md
Labels: gssoc, level3

#50 Unlabeled PR
  pr_dump/sharmi4590-pending-merged-Pr
Labels: gssoc, level3

#69 merged but project is removed from GSSOC
  pr_dump/unmerged_pr.md
Labels: gssoc, level3

#34 Create vishanurag.md
  pr_dump/vishanurag.md
Labels: gssoc, level3

#77 Create Pr-unmerged
  pr_dump/Pr-unmerged
Labels: gssoc, level3

#73 PR not merged under issue #340 in EcommerceSpectaStyle
  PR Chalsi Jain
Labels: gssoc, level3

#39 Create Sibam-Paul-pr.md
  pr_dump/Sibam-Paul-pr.md
Labels: gssoc, level3
